version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install

  pre_build:
    commands:
      - echo Retrieving environment variables...
      - aws ssm get-parameters-by-path --path "/portfolio/prod/" --with-decryption --region us-east-1 --output json | jq -r '.Parameters[] | .Name | split("/")[-1] + "=" + .Value' > .env
      - cat .env # Debugging: Check if .env is populated

  build:
    commands:
      - echo Build started on `date`
      - npm run build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://abe-dev-portfolio --delete

artifacts:
  base-directory: build
  files:
    - "**/*"
