version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g yarn
  
  pre_build:
    commands:
      - echo Retrieving environment variables...
      - aws ssm get-parameters-by-path --path "/portfolio/prod/" --with-decryption --region us-east-1 --output json | jq -r '.Parameters[] | .Name + "=" + .Value' > .env
      - yarn install

  build:
    commands:
      - echo Build started on `date`
      - yarn build

  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 sync build/ s3://abe-dev-portfolio --delete

artifacts:
  base-directory: build
  files:
    - '**/*'